name: Tune Submission
description: Submit a Tune for TerminalTunes
title: "[tune]: "
labels: ["tune"]
assignees:
  - startautomating
body:
  - type: markdown
    attributes:
      value: |
        Know a song?  Want to hear it to hear in in all of it's 8-bit glory?
  - type: textarea
    id: TuneSequence
    attributes:
      label: Tune
      description: The Tune Itself.  Please include escape sequences.
      render: PowerShell
    validations:
      required: true    
  - type: input
    id: TuneSource
    attributes:
      label: Tune Source
      description: The URL where you found the tune.
    validations:
      required: false
